services:
  tag-box-nginx:
    build:
      context: backend/docker/nginx
    volumes:
      - ./backend:/app
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - tag-box-swoole
      - tag-box-db
    networks:
      - tag-box-network
    restart: always # Automatically restart the container if it stops

  tag-box-swoole:
    build:
      context: backend/docker/php-swoole
    volumes:
      - ./backend:/app
    networks:
      - tag-box-network
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - tag-box-db
    environment:
      SHELL: /bin/bash
      OCTANE_SERVER: swoole
      OCTANE_WORKERS: auto
      OCTANE_HTTPS: false
      OCTANE_HOT_RELOAD: true

  tag-box-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: tag-box
    volumes:
      - db:/var/lib/mysql
      - ./logs/mysql/slow.log:/var/lib/mysql/slow.log
      - ./configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro  # ✅ Use custom config
    ports:
      - "33060:3306"
    networks:
      - tag-box-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  elasticsearch:
    image: elasticsearch:7.16.1
    volumes:
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    networks:
      - tag-box-network
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:8.17.0
    volumes:
      - ./configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - tag-box-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.1
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - tag-box-network
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    user: root
    entrypoint: filebeat -e -strict.perms=false
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access to Docker API
      - ./backend:/app
      - ./logs/mysql:/var/lib/mysql:ro
      - ./configs/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - tag-box-network
    depends_on:
      - logstash


networks:
  tag-box-network:
    driver: bridge

volumes:
  db:

