filebeat.inputs:
  - type: container
    # путь к лог-файлам контейнеров
    paths:
      - '/var/lib/docker/containers/*/*.log'

  - type: log
    paths:
      - "/logs/mysql/slow.log"  # ✅ Corrected path (relative to Filebeat container)
    fields:
      log_type: mysql_slow
    multiline.pattern: '^\# Time: '
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: [ "logstash:5044" ]

#filebeat.inputs:
#  - type: log
#    # путь к лог-файлам контейнеров
#    paths:
#      - '/app/storage/logs/daily/*.log'
#
#
#output.logstash:
#  hosts: [ "logstash:5044" ]
