# Use the official NGINX image
FROM nginx:1.23.2

# Set working directory
WORKDIR /etc/nginx

# Copy default configuration
COPY default.conf /etc/nginx/conf.d/default.conf

# Set working directory
WORKDIR /app

